packages:
  - "apps/*"
  - "backend"
  - "packages/*"
  - "tooling/*"

catalog:
  # TypeScript
  typescript: "^5.9.3"
  "@types/node": "^22.18.12"

  # React & Next.js
  react: "19.2.2"
  react-dom: "19.2.2"
  next: "16.1.3"
  "@types/react": "19.2.2"
  "@types/react-dom": "19.2.2"

  # Convex
  convex: "1.29.3"

  # Auth
  "@clerk/clerk-react": "5.57.1"
  "@clerk/nextjs": "6.36.8"
  "@clerk/themes": "^2.4.19"

  # ESLint
  eslint: "^9.39.1"
  "@eslint/js": "^9.39.1"
  "@eslint/compat": "2.0.0"

  # Prettier
  prettier: "^3.7.4"
  "@ianvs/prettier-plugin-sort-imports": "^4.7.0"
  prettier-plugin-tailwindcss: "^0.7.2"

  # Tailwind
  tailwindcss: "4.1.17"
  "@tailwindcss/postcss": "4.1.17"

  # Logging
  pino: "9.7.0"
  pino-pretty: "13.1.3"

  # Environment validation
  "@t3-oss/env-core": "0.12.0"
  "@t3-oss/env-nextjs": "^0.13.10"
  zod: "^4.1.12"

  # Testing
  vitest: "^3.2.4"
  "@vitest/coverage-v8": "3.3.4"

  # Turbo
  turbo: "2.6.2"
