packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@ai-sdk/provider': ^3.0.7
  '@ai-sdk/provider-utils': ^4.0.13
  '@clerk/clerk-react': 5.57.1
  '@clerk/nextjs': 6.37.1
  '@clerk/themes': ^2.4.51
  '@convex-dev/agent': github:get-convex/agent#rc/ai-sdk-v6
  '@convex-dev/rate-limiter': ^0.3.2
  '@eslint/compat': 2.0.2
  '@eslint/js': ^9.39.2
  '@ianvs/prettier-plugin-sort-imports': ^4.7.0
  '@next/eslint-plugin-next': 16.1.6
  '@openrouter/ai-sdk-provider': ^2.1.1
  '@radix-ui/react-avatar': ^1.1.11
  '@radix-ui/react-dialog': ^1.1.11
  '@radix-ui/react-dropdown-menu': ^2.1.16
  '@radix-ui/react-label': ^2.1.8
  '@radix-ui/react-popover': ^1.1.11
  '@radix-ui/react-scroll-area': ^1.2.10
  '@radix-ui/react-select': ^2.2.6
  '@radix-ui/react-slot': ^1.2.4
  cmdk: ^1.1.1
  '@t3-oss/env-core': 0.13.10
  '@t3-oss/env-nextjs': ^0.13.10
  '@tailwindcss/postcss': 4.1.18
  '@types/node': ^25.2.0
  '@types/react': 19.2.10
  '@types/react-dom': 19.2.3
  '@vitest/coverage-v8': 3.3.4
  ai: ^6.0.68
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  convex: 1.31.7
  eslint: ^9.39.2
  eslint-plugin-import: ^2.32.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-security: ^3.0.1
  eslint-plugin-sonarjs: ^3.0.6
  eslint-plugin-testing-library: ^7.15.4
  eslint-plugin-turbo: ^2.8.2
  eslint-plugin-unicorn: ^62.0.0
  jiti: ^2.6.1
  lucide-react: ^0.563.0
  next: 16.1.6
  next-themes: ^0.4.6
  pino: 10.3.0
  pino-pretty: 13.1.3
  postcss: ^8.5.6
  prettier: ^3.8.1
  prettier-plugin-tailwindcss: ^0.7.2
  react: 19.2.4
  react-dom: 19.2.4
  react-markdown: ^10.1.0
  remark-gfm: ^4.0.1
  shadcn: 3.8.2
  sonner: ^2.0.7
  tailwind-merge: ^3.4.0
  tailwindcss: 4.1.18
  turbo: 2.8.2
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  typescript-eslint: ^8.54.0
  vitest: ^4.0.18
  zod: ^4.3.6
